---
- name: Check for file f1 and if doesnot have execute permissions give it
  hosts: all
  tasks:
    - name: Check for file f1
      stat:
        path: /tmp/f1
      register: a
    - name: Display output of the module
      debug:
        var: a
    - name: Give execute permissions if not already present
      file:
        name: /tmp/f1
        mode: 700
      when: a.stat.executable == false
...
