---
- name: Implementing tags
  hosts: all
  tasks:
    - name: Install tree
      apt:
        name: tree
        state: present
      tags: tree_installation
    - name: Create user
      user:
        name: Ravi
        password: jayadeep
      tags: user_creation
    - name: Copy passwd file
      copy:
        src: /etc/passwd
        dest: /tmp
...
